import { beforeAll, describe, expect, it } from "vitest";
import fixture from "./stageRouting.fixture.json";
import { applyAIVariant } from "../aiVariant";
import { applyAction } from "../ai";
import { createInitialState } from "../rules";
import { findBestMoveVeryHard, lastDecision, cornerBookEnabled } from "./minimax";
import type { AIVariant } from "../aiVariant";
import type { GameState, Player } from "../types";

/**
 * Which stage handles a position, and what it plays there.
 *
 * Three defects in one session changed exactly this and nothing caught them: a
 * substitution moved ahead of a playability check so the book claimed a
 * different corner; a rule meant for the third stone in a corner refused the
 * second; and the larger-enclosure upgrade overruled stages that had just said
 * ground does not compete. In all three every flag held exactly the value it was
 * set to, so no amount of flag-checking would have noticed — what changed was
 * the decision.
 *
 * The fixture is generated by `generate-stage-fixture.mts` from the recorded
 * games, keeping only positions whose stage and move were identical across
 * three runs, so a case failing here is a change in the engine rather than a
 * slow machine.
 *
 * IT PINS TODAY'S BEHAVIOUR, BUGS INCLUDED. That is the point: a real
 * improvement will break cases here, and the fixture is then regenerated on
 * purpose. What it prevents is a decision changing silently as a side effect of
 * a rule added somewhere else — which is how all three of the above arrived.
 *
 * Regenerating: `npx vite-node generate-stage-fixture.mts`, then read the diff
 * before committing it. A change to one stage's cases is a change worth being
 * able to explain; a change to most of them means the ladder moved underneath.
 */
type Case = {
  stage: string;
  move: string;
  moves: Array<[number, number]>;
  engine: Player;
  /** Whether the move itself is a fact about the position or a coin-flip between
   * tied candidates. Set by `screen-stage-fixture.mts`; only the stable ones are
   * pinned, because a tolerance on the move assertion would hide a narrow real
   * regression as readily as it hides a tie. The unstable cases are still
   * covered by the routing assertion above. */
  moveStable?: boolean;
};
const { variant, budgetMs, cases } = fixture as {
  variant: AIVariant;
  budgetMs: number;
  cases: Case[];
};

const COLS = "ABCDEFGHI";
const nm = (row: number, col: number) => `${COLS[col]}${row + 1}`;

function decide(kase: Case) {
  let state: GameState = createInitialState();
  for (const [row, col] of kase.moves) state = applyAction(state, { type: "PLACE", row, col });
  const action = findBestMoveVeryHard(state, kase.engine, budgetMs);
  return {
    stage: lastDecision.stage,
    move: action.type === "PLACE" ? nm(action.row, action.col) : "PASS",
  };
}

describe("stage routing", () => {
  // Decided once and asserted twice: each case costs a full search at the
  // fixture's budget, so re-deciding for the second assertion doubled the
  // suite's runtime for nothing.
  const decided = new Map<Case, { stage: string; move: string }>();
  beforeAll(() => {
    applyAIVariant(variant);
    expect(cornerBookEnabled, "variant did not take").toBe(true);
    for (const kase of cases) decided.set(kase, decide(kase));
  }, 300_000);

  /**
   * The base stage is the routing decision — which rule owns this position.
   * Asserted separately from the move because the two fail for different
   * reasons and the distinction is most of the diagnosis.
   */
  it("routes every recorded position to the same stage", () => {
    const drifted: string[] = [];
    for (const kase of cases) {
      const got = decided.get(kase)!;
      const want = kase.stage.split(" +")[0];
      const mine = got.stage.split(" +")[0];
      if (mine !== want) drifted.push(`${kase.moves.length + 1}수: ${want} -> ${mine}`);
    }
    expect(drifted).toEqual([]);
  });

  it("plays the same move at each of them", () => {
    const drifted: string[] = [];
    const pinned = cases.filter((kase) => kase.moveStable);
    // If the screen has never run, everything is unscreened and this asserts
    // nothing — say so rather than passing quietly.
    expect(pinned.length, "no screened cases — run screen-stage-fixture.mts").toBeGreaterThan(0);
    for (const kase of pinned) {
      const got = decided.get(kase)!;
      if (got.move !== kase.move) {
        drifted.push(`${kase.stage} ${kase.moves.length + 1}수: ${kase.move} -> ${got.move}`);
      }
    }
    expect(drifted).toEqual([]);
  });
});
